runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main

runtime_config:
  python_version: 3

env_variables:
  GOOGLE_CLOUD_CREDENTIALS: './service-account.json'
  PROJECT_ID: knowledge-prototype
  PUBSUB_TOPIC: cyton-data
  PUBSUB_VERIFICATION_TOKEN: SECRET

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10